name: flutter_file_path_provider
description: flutter_file_path_provider 是一款用于读取设备上存储目录的 Flutter 插件，同时支持Android和iOS两个平台
version: 0.0.3
author: fiissh.zhao <zhaoyongchun2010@gmail.com>
homepage: https://github.com/fiissh/flutter_file_path_provider

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    androidPackage: tech.fiissh.flutter.plugin.provider
    pluginClass: FlutterFilePathProviderPlugin
